# Generated by Django 5.2.4 on 2025-08-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_quran_teacher',
            field=models.BooleanField(default=False, verbose_name='is quran teacher'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=True, verbose_name='is student'),
        ),
    ]
