# Generated by Django 5.2.4 on 2025-08-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_quran_teacher_customuser_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_quran_teacher',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
    ]
